# Generated by Django 5.2.7 on 2025-10-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Ингредиенты"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("кг", "Киллограмм"),
                            ("мг", "Миллиграм"),
                            ("г", "грамм"),
                        ],
                        default="г",
                        max_length=2,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название рецепта"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="receipts/", verbose_name="Картинка рецепта"
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
                ("cooking_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        verbose_name="Название тега",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
            ],
        ),
        migrations.CreateModel(
            name="IngredientInReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveSmallIntegerField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.ingredients",
                    ),
                ),
            ],
        ),
    ]
