# Generated by Django 5.2.7 on 2025-10-28 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Ингредиенты"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("кг", "Киллограмм"),
                            ("мг", "Миллиграм"),
                            ("г", "грамм"),
                        ],
                        default="г",
                        max_length=2,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        verbose_name="Название тега",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
            ],
        ),
        migrations.CreateModel(
            name="Receipts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название рецепта"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="receipts/", verbose_name="Картинка рецепта"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        to="food.ingredients", verbose_name="Ингредиенты"
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(to="food.tags", verbose_name="Тэг"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Покупатель"
                    ),
                ),
                (
                    "purchases",
                    models.ManyToManyField(
                        to="food.receipts", verbose_name="Покупки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteReceipts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "favorite_receipts",
                    models.ManyToManyField(
                        to="food.receipts", verbose_name="Избранное рецептов"
                    ),
                ),
            ],
        ),
    ]
