# Generated by Django 5.2.7 on 2025-10-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipts",
            old_name="description",
            new_name="text",
        ),
    ]
