# Generated by Django 5.2.7 on 2025-10-31 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("food", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritereceipts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="ingredientinreceipt",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food.ingredients",
            ),
        ),
        migrations.AddField(
            model_name="purchases",
            name="buyer",
            field=models.ManyToManyField(
                related_name="purchases_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="receipts",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="purchases",
            name="purchases",
            field=models.ManyToManyField(
                related_name="purchases_by",
                to="food.receipts",
                verbose_name="Покупки",
            ),
        ),
        migrations.AddField(
            model_name="ingredientinreceipt",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_ingredients",
                to="food.receipts",
            ),
        ),
        migrations.AddField(
            model_name="favoritereceipts",
            name="favorite_receipts",
            field=models.ManyToManyField(
                related_name="favorited_by",
                to="food.receipts",
                verbose_name="Избранное рецептов",
            ),
        ),
        migrations.AddField(
            model_name="receipts",
            name="tags",
            field=models.ManyToManyField(to="food.tags", verbose_name="Тэг"),
        ),
    ]
