# Generated by Django 5.2.7 on 2025-10-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteReceipts",
        ),
    ]
