# Generated by Django 5.2.7 on 2025-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipts",
            name="short_code",
            field=models.CharField(
                default="jke",
                max_length=3,
                unique=True,
                verbose_name="Короткий код",
            ),
            preserve_default=False,
        ),
    ]
