# Generated by Django 5.2.7 on 2025-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_description_receipts_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipts",
            name="cooking_time",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
