# Generated by Django 5.2.7 on 2025-10-28 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_receipts_cooking_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipts",
            old_name="tag",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="favoritereceipts",
            name="favorite_receipts",
            field=models.ManyToManyField(
                related_name="favorited_by",
                to="food.receipts",
                verbose_name="Избранное рецептов",
            ),
        ),
        migrations.AlterField(
            model_name="favoritereceipts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="buyer",
            field=models.ManyToManyField(
                related_name="purchases_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="purchases",
            field=models.ManyToManyField(
                related_name="purchases_by",
                to="food.receipts",
                verbose_name="Покупки",
            ),
        ),
    ]
